name: Deploy

on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --prune
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run generate
      - uses: peaceiris/actions-gh-pages@ba0b7df03e25ff29c924be8149041119e9421ea6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
