name: Deploy

on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --prune
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run generate
      - uses: webfactory/ssh-agent@4d1295c53b0ee6c012b6998f7155a09b271a52f5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        if: github.ref == 'refs/heads/master'
      - run: npm run deploy
        if: github.ref == 'refs/heads/master'
